@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.vfyjxf.justenoughgraphs.registration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;