@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.github.vfyjxf.justenoughgraphs.utils;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;